from app.services.tally import extract_time_and_quiz_name
from app.services.tally import extract_email_from_submission
from app.services.tally import extract_score_from_submission
from app.services.bamboo_hr import update_test_results
from app.services.bamboo_hr import get_employee_compensation
from app.services.bamboo_hr import update_jobinfo
from app.services.compensation import process_compensation_update, update_compensation
from app.services.bamboo_webhook import process_bamboo_webhook
from app.services.seven_shifts import create_seven_shifts_user
from app.services.seven_shifts import update_7shifts_user
from app.services.tally_service import process_tally_submission